all_class_hats = [
    "Antlers",
    "Virtual Viewfinder",
    "Polar Pullover",
    "Head Prize",
    "Potassium Bonnet",
    "Crone's Dome",
    "Captain Cardbeard Cutthroat",
    "Captain Space Mann",
    "Killer Exclusive",
    "Lucky Cat Hat",
    "Bedouin Bandana",
    "Balloonihoodie",
    "Onimann",
    "Hong Kong Cone",
    "Snowmann",
    "Ballooniphones",
    "Decorated Veteran",
    "Legendary Lid",
    "Aztec Warrior",
    "Prehistoric Pullover",
    "Candy Crown",
    "Brotherhood of Arms",
    "Rotation Sensation",
    "Jungle Wreath",
    "Crown of the Old Kingdom",
    "Towering Pile of Presents",
    "Tough Stuff Muffs",
    "Well-Rounded Rifleman",
    "Mister Bones",
    "Salty Dog",
    "Duck Billed Hatypus",
    "Breadcrab",
    "Co-Pilot",
    "Executioner",
    "Patriot Peak",
    "Bread Heads",
    "Merc's Mohawk",
    "Horrific Headsplitter",
    "Bone Cone",
    "All Hallows' Hatte",
    "Modest Pile of Hat",
    "Brown Bomber",
    "Dr's Dapper Topper",
    "Class Crown",
    "Lil' Bitey",
    "Hunter in Darkness",
    "Cotton Head",
    "Dark Falkirk Helm",
    "Law",
    "Vive La France",
    "Towering Patch of Pumpkins",
    "Federal Casemaker",
    "Galvanized Gibus",
    "Pithy Professional",
    "Woolen Warmer",
    "Company Man",
    "Toadstool Topper",
    "Smissmas Saxton",
    "A Well Wrapped Hat",
    "Hat Chocolate",
    "A Rather Festive Tree",
    "Kiss King",
    "Professional's Pom-Pom",
    "Chill Chullo",
    "Starlight Sorcerer",
    "Wrap-A-Khamon",
    "Modest Metal Pile of Scrap",
    "Tundra Top",
    "Alakablamicon",
    "Tipped Lid",
    "Towering Pillar of Hats",
    "Misfortune Fedora",
    "Human Cannonball",
    "Nasty Norsemann",
    "Hot Dogger",
    "Neckwear Headwear",
    "Noble Amassment of Hats",
    "Winter Woodsman",
    "Bot Dogger",
    "Towering Pillar of Beanies",
    "Reindoonibeanie",
    "Jolly Jester",
    "Universal Translator",
    "Caribou Companion",
    "Hat Outta Hell",
    "Coldsnap Cap",
    "Gnome Dome",
    "Boxcar Bomber",
    "Phononaut",
    "Smissmas Sorcerer",
    "Bumble Beenie",
    "El Fiestibrero",
    "Towering Titanium Pillar of Hats",
    "Twisted Topper",
    "Citizen Cane",
    "Sir Pumpkinton",
    "Hollowed Helm",
    "Beanie The All-Gnawing",
    "Noble Nickel Amassment of Hats",
    "Second-Head Headwear",
    "Merry Cone",
    "Seasonal Spring",
    "Bat Hat",
    "Giftcrafter",
    "Shoestring Santa",
    "Globetrotter",
    "Jolly Jingler",
    "Reindoonihorns",
    "King Cardbeard",
    "Cozy Catchers",
    "Yule Hog",
    "A Handsome Handy Thing",
    "Spooky Head-Bouncers",
    "Undercover Brolly",
]

quick_switch_hats = [
    "Herald's Helm",
    "Whirly Warrior",
    "Cranial Cowl",
    "Wandering Wraith",
    "Blast Defense",
    "Frag Proof Fragger",
    "Gauzed Gaze",
    "Das Hazmattenhatten",
]
